[package]
name = "schema"
version = "0.1.0"
edition = "2024"

[lib]
path = "./src/lib.rs"

[dependencies]
ignore = "0.4.25"
memmap2 = "0.9.9"
ouroboros = "0.18.5"
tree-sitter = "0.26.5"
tree-sitter-python = "0.25.0"

# [profile.release]
# lto = "thin"
# codegen-units = 1
